version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: filedb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
      - mongo
      - redis
      - etherpad
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: filedb
      DB_USER: root
      DB_PASSWORD: password
      MONGO_URI: mongodb://mongo:27017/filedb
      ETHERPAD_API_URL: http://etherpad:9001/api/1
      ETHERPAD_API_KEY: apikey
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  etherpad:
    image: etherpad/etherpad
    restart: always
    environment:
      API_KEY: apikey
    ports:
      - "9001:9001"
volumes:
  db_data:
  mongo_data:
  redis_data:
