spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:h2:mem:filedb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path : /h2-console
  data:
    mongodb:
      uri: mongodb://localhost:27017/filedb
logging:
  level:
    root: INFO
    in.lazygod: DEBUG
  

jwt:
  secret : YourSecretKeyHereYourSecretKeyHereYourSecretKeyHereYourSecretKeyHere
  expiration:
    hr: 10

storage:
  id: default-local
  type: LOCAL
  access_id :
  access_key :
  local:
    base-path: /Users/sachin/IdeaProjects/filemanager/dummy_storage

system:
  admin:
    username: admin
    email: admin@example.com
    password: admin123

admin:
  server:
    port: 9090

snowflake:
  node-id: 1

encryption:
  secret: 12345678901234567890123456789012

ratelimit:
  enabled: true
  limit: 60

cluster:
  enabled: false

etherpad:
  api-url: http://localhost:9001/api/1
  api-key: apikey
