server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: true

spring:
  application:
    name: filemanager
  messages:
    basename: messages
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:filedb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/filedb}

logging:
  level:
    root: INFO
    in.lazygod: DEBUG

jwt:
  secret : YourSecretKeyHereYourSecretKeyHere
  expiration:
    hr: 10

storage:
  id: default-local
  type: LOCAL
  access_id :
  access_key :
  local:
    base-path: /Users/sachin/IdeaProjects/filemanager/dummy_storage

system:
  admin:
    username: admin
    email: admin@example.com
    password: admin123

admin:
  server:
    port: 9090

snowflake:
  node-id: 1

encryption:
  secret: ChangeThisSecretKey123

ratelimit:
  enabled: true
  limit: 60
cache:
  ttl: 60

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

roster:
  ttl:
    ms: 60000

cluster:
  enabled: false
