server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:filedb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
    in.lazygod: DEBUG

storage:
  id: default-local
  type: LOCAL
  access_id :
  access_key :
  local:
    base-path: /Users/sachin/IdeaProjects/filemanager/dummy_storage

system:
  admin:
    username: admin
    email: admin@example.com
    password: admin123

snowflake:
  node-id: 1
